### PR TITLE
For id="time", the attribute value of attribute-type/origin/as should…

### PR DESCRIPTION
**Pull request by colourful-land**
Addressing @hboon questions:

> For id="time", should the attribute value of attribute-type/origin/as be mapping instead?

Yes. Me bad!

> How do we tell that the attribute-type above is of type BinaryTime? The previous version has a type attribute.

We don't tell. Anything using "mapping" we ignore the value format. The BinaryTime comment is for another human to see that the key values being not "1, 2, 3" for a backward compatibility reason (that it was BinaryTime format a month ago but we redefined it). I hope it makes sense:)

> Do we fallback to the sole <value> element when there's no lang attribute? The earlier version always had a lang attribute for all <value> elements.

The old Java hardcoded rule is that if there is no matching "lang", use the 1st value discovered, hence no special treatment needed for the first <value> element that doesn't have "lang". I'm thinking of keeping this rule and generalize it (always default to 1st value), how do you think?

> Also for <value>, do we fallback to the element with lang="en" if no match is found?

No, fall back to the first <value>. The logic being that English is not the default and the XML author knows better which language is the default. e.g. in FIFIA, the venue names default to Russian while the ticket category defaults to English. The rationale being that an Arabic user might need to match the Russian venue name against road signs while not being familiar with English, but he doesn't need to do the same with ticket Category in English.

The code I used is:

    String getLocalisedName(Element nameContainer) {
        Element name = null;
        Locale currentNodeLang;
        for(Node node=nameContainer.getLastChild();
            node!=null; node=node.getPreviousSibling()){
            if (node.getNodeType() == Node.ELEMENT_NODE && node.getNodeName().equals("name")) {
                // System.out.println("\nFound a name field: " + node.getNodeName());
                name = (Element) node;
                currentNodeLang = new Locale(name.getAttribute("lang"));
                if (currentNodeLang.getLanguage().equals(locale.getLanguage())) {
                    return name.getTextContent();
                }
            }
        }
        return name != null ? name.getTextContent() : " "; /* Should be the first occurrence of <name> */
    }

> <fields>

corrected. Thank you very much.

### CODE REVIEW

**Comment by hboon** [comment]
@colourful-land 

All good except:

> We don't tell. Anything using "mapping" we ignore the value format. The BinaryTime comment is for another human to see that the key values being not "1, 2, 3" for a backward compatibility reason (that it was BinaryTime format a month ago but we redefined it). I hope it makes sense:)

I don't follow. Are you saying to use the value verbatim as a string? But say, (A) we extract this from the mapping:

```
<value>20180614180000+0300</value>
```

And In the UI, (B) we need to display (depending on locale):

```
Jun 14, 2018
```

How do we get from (A) to (B) without knowing that it is a date?

I was hoping we can use the parser with something like this in the app (client code) pseudo code:

```
Date time = Parser new(xml, token).extract("time", "en")
```

**Comment by colourful-land** [comment]
@hboon I tried to call you because I have a career habit not to write to address a misunderstanding caused in writing (i.e. call to address the misunderstanding in writing).

**Comment by colourful-land** [comment]
Nevermind the quirky way objects are named in X.509 and ASN.1, just hardcode 1.3.6.1.4.1.1466.115.121.1.24 to be generalised time. If you google for 1.3.6.1.4.1.1466.115.121.1.24 you can get the original X.208 standard text but the format is so simple that you probably don't need it.

On the UI, currently we default to the timezone given in the generalized time. , not user's current GPS timezone.

**Comment by colourful-land** [comment]
By the way when you are happy with this pull request kindly approve it

**Comment by colourful-land** [comment]
> In the context of computer security, OIDs name nearly all X.509 certificate object types, including components of policies, distinguished names, CPSs, and so on. OIDs are associated with objects in data structures defined using the standard Abstract Syntax Notation number One (ASN.1) so that OIDs may be generated and processed by client and server software.

https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSig/oids.html

A ticket satisfy the technical definition of a certificate.

**Comment by hboon** [comment]
Thanks it clearing it up. Good to merge.

**Comment by hboon** [comment]
@colourful-land upon re-reading I realised I missed your question here:

> The old Java hardcoded rule is that if there is no matching "lang", use the 1st value discovered, hence no special treatment needed for the first element that doesn't have "lang". I'm thinking of keeping this rule and generalize it (always default to 1st value), how do you think?

Initially I thought it might be better to add an attribute like this:

```
<value lang="ru">Москва́</value>
<value lang="en" fallback="true">Moscow</value>
```

But I think defaulting to the 1st value is better and simpler. Both Android and iOS supports having a list of preferred locales (or languages). This also leaves more room for working with that.

**Pull request merged**
