### PR TITLE
Update TicketingContract.xml

### PR DESCRIPTION
**Pull request by zhangzhongnan928**
Prepare for RISE 2018

City: 232 Hong Kong
Venue: 237 Hong Kong Convention and Exhibition Centre
Date: one of 9th July- 12 July
Time: 09:00-18:00
Team A and Team B: AWT-INV
Cat: 246 AlphaWallet Meeting Slot
Match number: M1

### CODE REVIEW

**Comment by colourful-land** [comment]
This work must be redone because the XML has changed. Sangalli can you do this? Victor is overseas so I assume its easier if you do it. @James-Sangalli

**Comment by lyhistory** [comment]
fixing now, will commit it later

**Comment by lyhistory** [comment]
oh, I don't have commit permission to this repository,
BTW, I added city venue category, but not sure how to add Team and Match number, for DateTime, I find in current sample:
<option key="1528988400">
          <value>20180614180000+0300</value>
</option>
fixed datetime value, not sure how to add a datetime range


> remote: Permission to alpha-wallet/contracts.git denied to lyhistory.
> fatal: unable to access 'https://github.com/alpha-wallet/contracts.git/': The requested URL returned error: 403

**Comment by lyhistory** [comment]
just for your info:
there is a existing 'Hong kong' city in master branch which the key is 245, anyway I added 232, so now hongkong city is duplicated

**Comment by colourful-land** [comment]
- the version is still in conflict with the master branch.
- the branch diverged from master too much. You will save some time by simply copying the current master version over and redo what victor did in the new XML format.
- don't add the duplicated key, just inform Victor about it.

**Comment by colourful-land** [comment]
You said:
> I only added city venue category, 
> but not sure how to add Team and Match number,
> is it also like
    <option key="AWT">
          <value>AWT</value>
        </option>
    <option key="M1">
          <value>M1</value>
        </option>

My answer:

Observe that key is always a number.

**Comment by colourful-land** [comment]
When you managed to achieve this, the branch is good for me.

Type

    $ git diff master..zhangzhongnan928-patch-1

and you get only about 16 lines of output.

**Comment by lyhistory** [comment]
commited, added teamA teamB match, sorry but how about the datetime range @colourful-land

**Comment by colourful-land** [comment]
As said, the branch diverted from master too much.

I'll merge it if:

    $ git diff master..zhangzhongnan928-patch-1

has only about 16 lines of output.

currently 1313 lines.

    $ git diff master..zhangzhongnan928-patch-1 | wc -l
     1313

**Comment by lyhistory** [comment]
now the date time in master are 

        <option key="1528988400">
          <value>20180614180000+0300</value>
        </option>
fixed datetime and the timezone is +3
so for hongkong should I use timezone +8,
if not wrong, supposed to translate:
Date: one of 9th July- 12 July
Time: 09:00-18:00
to 
20180709090000+0800 and 20180712180000+0800

**Comment by lyhistory** [comment]
strange, from my side, there is only few lines of change when I 
git diff master..zhangzhongnan928-patch-1

**Comment by colourful-land** [comment]
````
$ git pull
Enter passphrase for key '/home/weiwu/.ssh/id_ecdsa': 
Already up-to-date.
$ git diff master..zhangzhongnan928-patch-1 | wc -l
1313
````

Is it possible that you are working on a different branch than this pull request?

**Comment by lyhistory** [comment]
ok, let me create a new branch, minutes

**Comment by James-Sangalli** [comment]
@colourful-land Works for me, please check you are up to date

**Comment by colourful-land** [comment]
Doh!! Okay, thanks @James-Sangalli sorry @lyhistory I forgot to make sure master was updated. Was drinking Maotao while doing this.

**Comment by lyhistory** [comment]
new merge request:
https://github.com/alpha-wallet/contracts/pull/20

**Comment by lyhistory** [comment]
oh, ic, then please ignore the new pull request, just wondering whether something wrong with my editor :)

**Comment by hboon** [comment]
These 2 lines:

```
<origin as="utf8" bitmask="00000000000000000000000000000000000000000000FFFFFF00000000000000">
<origin as="utf8" bitmask="00000000000000000000000000000000000000000000000000FFFFFF00000000">
```

should say:

```
<origin as="mapping" ...
<origin as="mapping" ...
```

instead.

**Comment by colourful-land** [comment]
Bhoon you are right. Please correct it again and I'll merge.

**Comment by lyhistory** [comment]
updated, please check

**Comment by hboon** [comment]
@lyhistory

Date: one of 9th July- 12 July
Time: 09:00-18:00

should be mapped to 4 `<option>`(s), i.e 9, 10, 11, 12. So if you want all of them to start at 9am:

20180709090000+0800
20180710090000+0800
20180711090000+0800
20180712090000+0800

I'm *guessing* if you want a few more of these, spread them apart, 1 or 2 hours apart, 9am, 11am, 1pm etc? The exact time isn't that important, right?

PS: hope I beat @colourful-land before signing.

**Comment by colourful-land** [comment]
@hboon hey I'm high on Maotai but I can still tell that countryA, countryB should be utf8 and match should be 'unsigned' because that was how it was encoded. Which means we are wasting our time since the beginning (not wasting, if counting in the learning). The fact is:

1. Victor's wish to change country A and country B is done through embedding value directly into the 256-bit TokenID.

2. Victor's wish to change Match to add M1 should be, be, be... be done by the app code, not by data source because only 1 byte is left for that thingy.

I hope you read some sense between the lines.

**Comment by colourful-land** [comment]
The syntax of countryA and countryB are IA5String, which excludes most UTF-8 characters, but the value is encoded in UTF8 since it is about string encoding not about validity.

**Comment by colourful-land** [comment]
My suggestion, for now, is that we reverse everything Victor suggested because it is either not done in XML or not doable in XML, then we add @hboon's fix, then we close this.

**Comment by lyhistory** [comment]
ok, a little bit mess up in my mind, then should I change back to previous version

**Pull request merged**
